[workspace]
authors = ["Nathan P <nathan.w.pulver@gmail.com>"]
channels = ["conda-forge"]
name = "pyhy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
dash = ">=3.2.0,<4"
numpy = ">=2.3.4,<3"
matplotlib = ">=3.10.7,<4"
pandas = ">=2.3.3,<3"
plotly = ">=6.4.0,<7"
scipy = ">=1.16.3,<2"
